kind: CronJob
apiVersion: batch/v1
metadata:
  name: ad-group-sync
  namespace: ad-sync
  uid: 74ebfb24-0497-46f9-88b4-a5100fcf7e89
  resourceVersion: '41471930'
  generation: 1
  creationTimestamp: '2023-09-07T07:00:48Z'
  managedFields:
    - manager: OpenAPI-Generator
      operation: Update
      apiVersion: batch/v1
      time: '2023-09-07T07:00:48Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:concurrencyPolicy': {}
          'f:failedJobsHistoryLimit': {}
          'f:jobTemplate':
            'f:spec':
              'f:template':
                'f:spec':
                  'f:volumes':
                    .: {}
                    'k:{"name":"config"}':
                      .: {}
                      'f:name': {}
                      'f:secret':
                        .: {}
                        'f:defaultMode': {}
                        'f:secretName': {}
                  'f:containers':
                    'k:{"name":"oc-cli"}':
                      'f:image': {}
                      'f:volumeMounts':
                        .: {}
                        'k:{"mountPath":"/ad-sync/"}':
                          .: {}
                          'f:mountPath': {}
                          'f:name': {}
                          'f:readOnly': {}
                      'f:terminationMessagePolicy': {}
                      .: {}
                      'f:resources': {}
                      'f:command': {}
                      'f:terminationMessagePath': {}
                      'f:imagePullPolicy': {}
                      'f:name': {}
                  'f:dnsPolicy': {}
                  'f:serviceAccount': {}
                  'f:restartPolicy': {}
                  'f:schedulerName': {}
                  'f:terminationGracePeriodSeconds': {}
                  'f:serviceAccountName': {}
                  'f:securityContext': {}
          'f:schedule': {}
          'f:successfulJobsHistoryLimit': {}
          'f:suspend': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: batch/v1
      time: '2023-10-04T13:00:08Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:lastScheduleTime': {}
          'f:lastSuccessfulTime': {}
      subresource: status
spec:
  schedule: '*/30 * * * *'
  concurrencyPolicy: Forbid
  suspend: false
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          restartPolicy: Never
          serviceAccountName: ad-sync
          schedulerName: default-scheduler
          terminationGracePeriodSeconds: 30
          securityContext: {}
          containers:
            - name: oc-cli
              image: >-
                jfrog-caas.internal.vodafone.nl/caas-mobile-containers-virtual/ose-cli:4.12
              command:
                - /bin/oc
                - adm
                - groups
                - sync
                - '--sync-config=/ad-sync/ADGroupSync.yaml'
                - '--confirm'
              resources: {}
              volumeMounts:
                - name: config
                  readOnly: true
                  mountPath: /ad-sync/
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: Always
          serviceAccount: ad-sync
          volumes:
            - name: config
              secret:
                secretName: ad-sync
                defaultMode: 420
          dnsPolicy: ClusterFirst
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
status:
  lastScheduleTime: '2023-10-04T13:00:00Z'
  lastSuccessfulTime: '2023-10-04T13:00:08Z'
