kind: CronJob
apiVersion: batch/v1
metadata:
  name: cli-check
  namespace: default
spec:
  schedule: '*/3 * * * *'
  concurrencyPolicy: Forbid
  suspend: false
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          restartPolicy: Never
          serviceAccountName: ad-sync
          schedulerName: default-scheduler
          terminationGracePeriodSeconds: 30
          securityContext: {}
          containers:
            - name: oc-cli
              image: >-
                openshift/ose-cli:4.12
              command:
                - /bin/oc
                - get
                - node
              resources: {}
             
