apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    openshift.io/prometheus-rule-evaluation-scope: leaf-prometheus
  name: watchdogdown-alerting-rule-1
  namespace: openshift-monitoring
spec:
  groups:
  - name: watchdog
    rules:
    # Alert if the watchdog alert is not firing for more than 5 minutes
    - alert: WatchdogDown
      expr: {alertname="Watchdog"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Watchdog alert is not firing"
        description: "The alerting pipeline might be broken, check Alertmanager and Prometheus"

  # Alert if the watchdog alert is firing again after being down
    - alert: WatchdogUp
      expr: {alertname="Watchdog"} == 1 or {alertname="WatchdogDown"} == 0
      labels:
        severity: info
      annotations:
        summary: "Watchdog alert is firing again"
        description: "The alerting pipeline is restored, clear the WatchdogDown alert"
